[workspace]
members = [
    "server",
    "client",
    "shared",
]

[patch.crates-io]
pathfinder_geometry = { git = "https://github.com/servo/pathfinder" }
pathfinder_simd = { git = "https://github.com/servo/pathfinder" }
